### ISSUE TITLE
new module

### ISSUE THREAD

**Issue by manuelduarte077** [Navis-code/recursos-recursos-recursos#29]
Hello, I think a mobile session would be good, I know some resources that can help

**Comment by durbonca** [comment]
¡Hola, Manuel! ¡Siempre puedes crear nuevas categorías agregándolas con el recurso nuevo! agrega el recurso nuevo y en "categoryName": "nombre-de-la-nueva-categoría-que-crees-que-puede-funcionar" 

Intenta de que el nombre sea lo más descriptivo posible sin ser tan largo como el mío jajaja. Todos los aportes son bienvenidos. Esperamos el tuyo <3 y gracias nuevamente por aportar

**Comment by manuelduarte077** [comment]
Ok, Muchas Gracias, vamos hacerlo 🔥
